### DISCUSSION TITLE
Facilitate citation of the MSL

### DISCUSSION THREAD

**Discussion by tobolar** [modelica/ModelicaStandardLibrary#3907] [Ideas]
To my knowledge, there is actually no advice how to cite the Modelica Standard Library software. Recently, I've discovered a possibility to add the CITATION.cff file to facilitate this.
- https://citation-file-format.github.io/

The GitHub even supports this format and some other tools do so as well: https://github.com/citation-file-format/citation-file-format/blob/main/README.md
Could this be a way for MSL as well?

**Comment by beutlich** [comment]
Yes, this is a valuable option. I already played with CITATION.cff some time ago and noticed that `preferred-citation` is not supported by all tools. `preferred-citation` is useful if you have a prefer citation redirection to an already available reference, instead of just the repository itself. For MSL software this is not the case as there is no standard publication. Thus, I appreciate the effort to add

```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it using these metadata."
authors:
  - name: "Modelica Association and contributors"
license: BSD-3-Clause
title: "Modelica Standard Library"
version: 4.0.0
date-released: "2020-06-04"
repository-code: "https://github.com/modelica/ModelicaStandardLibrary"
```
